stages:
    - test
    - build
    - deploy

test-job:
    tags:
        - test
    stage: test
    script:
        - yarn install
        - yarn run check

build-job:
    tags:
        - build
    stage: build
    script:
        - yarn install
        - yarn build

#deploy-job:
#    tags:
#        - deploy
#    stage: deploy
#    script:
#        - node -v
