stages:
    - test
    - build
    - deploy

test:
    stage: test
    tags:
        - test
    script:
        - yarn install
        - yarn run check

build:
    stage: build
    tags:
        - build
    script:
        - yarn install
        - yarn build

deploy:
    tags:
        - deploy
    stage: deploy
    script:
        - docker-compose up -d --build
